### ISSUE TITLE
compile.bat

### ISSUE THREAD

**Issue by lowercase-donkey** [Free-Cities/Free-Cities#844]
Compile.bat cannot be run as admin and it cannot be called from another program (like notepad++).  In either case, it fails saying it cannot find files.  Is there a better way to format it, or some sort of dickery with shortcuts?

I don't care about running as admin, but running it from notepad would be very handy for quick compiling.

**Comment by MegaPramuk** [comment]
Sounds like command line isn't in the directory of Free-Cities.
But, [apparently](https://stackoverflow.com/questions/921741/windows-equivalent-to-unix-pwd), calling cd with no arguments gives the current directory. Try to do that.
Does it differ from the Free-Cities one? 
If so, it'd be fixable but not universal unless a certain hierarchy is to be enforced, afaik.

**Comment by IWantToBeAnonymous** [comment]
Should be fixed assuming [#851](https://github.com/Free-Cities/Free-Cities/pull/851) gets merged. Not 100% about it running through notepad++ though.

**Comment by lowercase-donkey** [comment]
#851 doesn't seem to fix it on my machine, @IWantToBeAnonymous .
